name: career_fair_web
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  url_launcher: ^6.1.11
  flutter_timer_countdown: ^1.0.7
  flutter_screenutil: ^5.9.3
  pattern_background: ^1.1.3
  galleryimage: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/gallery/
    # - assets/icons/
    # - assets/fonts/
