name: career_fair_web
description: "Career Fair 2025 - ENTC"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  # url_launcher: ^6.1.11
  flutter_timer_countdown: ^1.0.7
  video_player: ^2.9.2
  web_video_player: ^0.0.1-dev.2
  flutter_widget_from_html: ^0.15.3
  url_launcher: ^6.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/gallery/
    - assets/videos/
    # - assets/icons/
    # - assets/fonts/
